package com.kosrvd.app.core.presentation.designsystem.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006877)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFA4EEFF)
val onPrimaryContainerLight = Color(0xFF004E5A)
val secondaryLight = Color(0xFF4B6268)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCDE7ED)
val onSecondaryContainerLight = Color(0xFF334A50)
val tertiaryLight = Color(0xFF545D7E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFDCE1FF)
val onTertiaryContainerLight = Color(0xFF3D4565)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF5FAFC)
val onBackgroundLight = Color(0xFF171D1E)
val surfaceLight = Color(0xFFF5FAFC)
val onSurfaceLight = Color(0xFF171D1E)
val surfaceVariantLight = Color(0xFFDBE4E7)
val onSurfaceVariantLight = Color(0xFF3F484B)
val outlineLight = Color(0xFF6F797B)
val outlineVariantLight = Color(0xFFBFC8CB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3133)
val inverseOnSurfaceLight = Color(0xFFECF2F3)
val inversePrimaryLight = Color(0xFF83D2E4)
val surfaceDimLight = Color(0xFFD5DBDD)
val surfaceBrightLight = Color(0xFFF5FAFC)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF4F6)
val surfaceContainerLight = Color(0xFFE9EFF0)
val surfaceContainerHighLight = Color(0xFFE3E9EB)
val surfaceContainerHighestLight = Color(0xFFDEE3E5)